apiVersion: apps/v1
kind: Deployment
metadata:
  name: dps-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: dps-api-deployment
  template:
    metadata:
      labels:
        type: dps-api-deployment
    spec:
      containers:
        - name: dps-api-deployment
          image: duynguyenngoc/dps-api:latest
          imagePullPolicy: Always 
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dp-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    type: dps-api-deployment