  # hbase:
  #   image: yulin/hbase-standalone:1.0.1-hbase2.0.0
  #   container_name: hbase
  #   hostname: hbase
  #   volumes:
  #     - hbase_data:/hbase-data
  #     - hbase_zookeeper_data:/zookeeper-data
  #   ports:
  #     - 16000:16000
  #     - 16010:16010
  #     - 16020:16020
  #     - 16030:16030
  #     - 2888:2888
  #     - 3888:3888
  #     - 2181:2181
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
  #   env_file:
  #     - ./hbase-standalone.env