name: DEPLOY_PRODUCTION
on:
  pull_request:
    branches:
      - main
    paths: 
      - 'dps-spark/**'

env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} # dockerhub pass
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} # dockerhub user
  IMAGE: duynguyenngoc/dps-hadoop-spark:3.3.1 # Image docker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      # [Step-1] check config git
      - name: Checkout
        uses: actions/checkout@v2
      # [Step-2] login dockerhub container
      - name: Login to DockerHub Registry
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      # [Step-3] buid and tag image from Dockerfile
      - name: Build docker image
        run: |
          docker build -t $IMAGE --no-cache ./dps-hadoop-spark/
      # [Step-4] Push image to docker hub
      - name: Push image to DockerHub
        run: |
          docker push $IMAGE